# permissions for end users to view releaseserviceconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: releaseserviceconfig-viewer-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: 'true'
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - releaseserviceconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - appstudio.redhat.com
  resources:
  - releaseserviceconfigs/status
  verbs:
  - get
